# Generated by Django 2.2.19 on 2022-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('model_number', models.CharField(max_length=255, unique=True, verbose_name='Артикул товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('status', models.CharField(choices=[('В наличи', 'В наличии'), ('Под заказ', 'Под заказ'), ('Ожидается поступление', 'Ожидается поступление'), ('Нет в наличии', 'Нет в наличии'), ('Не производится', 'Не производится')], default='В наличи', max_length=20, verbose_name='Статус товара')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
