# Generated by Django 3.2.16 on 2022-12-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='new_format',
            new_name='new_image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='old_format',
            new_name='old_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.image', verbose_name='Изображение товара'),
        ),
    ]
