# Generated by Django 3.2.16 on 2022-12-13 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Изображение товара')),
                ('primary_format', models.CharField(max_length=25)),
                ('old_image', models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Старое изображение товара')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ'), ('Ожидается поступление', 'Ожидается поступление'), ('Нет в наличии', 'Нет в наличии'), ('Не производится', 'Не производится')], default='В наличии', max_length=25, verbose_name='Статус товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.image', verbose_name='Изображение товара'),
            preserve_default=False,
        ),
    ]
