# Generated by Django 3.2.16 on 2022-12-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20221213_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.image', verbose_name='Изображение товара'),
        ),
    ]
