# Generated by Django 3.2.16 on 2022-12-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='primary_format',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
