# Generated by Django 3.2.16 on 2022-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20221214_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='old_image',
        ),
        migrations.AddField(
            model_name='image',
            name='new_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='old_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='new_image',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
