# Generated by Django 3.2.16 on 2022-12-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20221214_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='new_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
    ]
